from mappings.english_to_braille import (
    ENGLISH_TO_BRAILLE_ALPHABET_MAPPING,
    NUMBER_TO_BRAILLE_MAPPING,
    SPECIAL_TO_BRAILLE_MAPPING,
    NOT_POSSIBLE_NUMBER_OPERATORS_MAPPING
)

BRAILLE_TO_ENGLISH_ALPHABET_MAPPING = {val: key for key, val in ENGLISH_TO_BRAILLE_ALPHABET_MAPPING.items()}
BRAILLE_TO_NUMBERS_MAPPING = {val: key for key, val in NUMBER_TO_BRAILLE_MAPPING.items()}
BRAILLE_TO_SPECIAL_CHARS_MAPPING = {val: key for key, val in SPECIAL_TO_BRAILLE_MAPPING.items()}
BRAILLE_NOT_POSSIBLE_NUMBER_OPERATORS_TO_SPECIAL_CHARS_MAPPING = {val: key for key, val in NOT_POSSIBLE_NUMBER_OPERATORS_MAPPING.items()}
