export const BRAILLE_REFERENCE = [
  { value: "a", braille: "O....." },
  { value: "b", braille: "O.O..." },
  { value: "c", braille: "OO...." },
  { value: "d", braille: "OO.O.." },
  { value: "e", braille: "O..O.." },
  { value: "f", braille: "OOO..." },
  { value: "g", braille: "OOOO.." },
  { value: "h", braille: "O.OO.." },
  { value: "i", braille: ".OO..." },
  { value: "j", braille: ".OOO.." },
  { value: "k", braille: "O...O." },
  { value: "l", braille: "O.O.O." },
  { value: "m", braille: "OO..O." },
  { value: "n", braille: "OO.OO." },
  { value: "o", braille: "O..OO." },
  { value: "p", braille: "OOO.O." },
  { value: "q", braille: "OOOOO." },
  { value: "r", braille: "O.OOO." },
  { value: "s", braille: ".OO.O." },
  { value: "t", braille: ".OOOO." },
  { value: "u", braille: "O...OO" },
  { value: "v", braille: "O.O.OO" },
  { value: "w", braille: ".OOO.O" },
  { value: "x", braille: "OO..OO" },
  { value: "y", braille: "OO.OOO" },
  { value: "z", braille: "O..OOO" },
  { value: "1", braille: "O....." },
  { value: "2", braille: "O.O..." },
  { value: "3", braille: "OO...." },
  { value: "4", braille: "OO.O.." },
  { value: "5", braille: "O..O.." },
  { value: "6", braille: "OOO..." },
  { value: "7", braille: "OOOO.." },
  { value: "8", braille: "O.OO.." },
  { value: "9", braille: ".OO..." },
  { value: "0", braille: ".OOO.." },
  { value: " ", braille: "......" },
];

export const BRAILLE_SIGNS = [
  { value: "CAPITAL", braille: ".....O" },
  { value: "NUMBER", braille: ".O.OOO" },
  { value: " ", braille: "......" },
];

export const BRAILLE_NUMBERS = [
  { value: "1", braille: "O....." },
  { value: "2", braille: "O.O..." },
  { value: "3", braille: "OO...." },
  { value: "4", braille: "OO.O.." },
  { value: "5", braille: "O..O.." },
  { value: "6", braille: "OOO..." },
  { value: "7", braille: "OOOO.." },
  { value: "8", braille: "O.OO.." },
  { value: "9", braille: ".OO..." },
  { value: "0", braille: ".OOO.." },
];

export const BRAILLE_REGEX = /^[O.]+$/;
