const translation = {
    A: 'O.....',
    B: 'O.O...',
    C: 'OO....',
    D: 'OO.O..',
    E: 'O..O..',
    F: 'OOO...',
    G: 'OOOO..',
    H: 'O.OO..',
    I: '.OO...',
    J: '.OOO..',
    K: 'O...O.',
    L: 'O.O.O.',
    M: 'OO..O.',
    N: 'OO.OO.',
    O: 'O..OO.',
    P: 'OOO.O.',
    Q: 'OOOOO.',
    R: 'O.OOO.',
    S: '.OO.O.',
    T: '.OOOO.',
    U: 'O...OO',
    V: 'O.O.OO',
    W: '.OOO.O',
    X: 'OO..OO',
    Y: 'OO.OOO',
    Z: 'O..OOO',
    capitalLetterSign: '.....O',
    numberSign: '.O.OOO',
    decimalPoint: '.O...O',
    dot: '..OO.O',
    coma: '..O...',
    question: '..O.OO',
    exclamation: '..OOO.',
    twoDots: '..OO..',
    dotComa: '..O.O.',
    hyphen: '....OO',
    slash: '.O..O.',
    minor: '.OO..O',
    mayor: 'O..OO.',
    openParentesis: 'O.O..O',
    closeParentesis: '.O.OO.',
    space: '......'
};

const especialCharacters = {
    '.': 'dot',
    ',': 'coma',
    '?': 'question',
    '!': 'exclamation',
    ':': 'twoDots',
    ';': 'dotComa',
    '-': 'hyphen',
    '/': 'slash',
    '<': 'minor',
    '>': 'mayor',
    '(': 'openParentesis',
    ')': 'closeParentesis',
    ' ': 'space'
};

const valuesArray = [
    '.',
    ',',
    '?',
    '!',
    ':',
    ';',
    '-',
    '/',
    '<',
    '>',
    '(',
    ')',
    ' '
];

const numbers = {
    '1': 'O.....',
    '2': 'O.O...',
    '3': 'OO....',
    '4': 'OO.O..',
    '5': 'O..O..',
    '6': 'OOO...',
    '7': 'OOOO..',
    '8': 'O.OO..',
    '9': '.OO...',
    '0': '.OOO..',
} 

module.exports = {translation, especialCharacters, valuesArray, numbers};
