export const brailleDictionary = {
  a: 'O.....',
  b: 'O.O...',
  c: 'OO....',
  d: 'OO.O..',
  e: 'O..O..',
  f: 'OOO...',
  g: 'OOOO..',
  h: 'O.OO..',
  i: '.OO...',
  j: '.OOO..',
  k: 'O...O.',
  l: 'O.O.O.',
  m: 'OO..O.',
  n: 'OO.OO.',
  o: 'O..OO.',
  p: 'OOO.O.',
  q: 'OOOOO.',
  r: 'O.OOO.',
  s: '.OO.O.',
  t: '.OOOO.',
  u: 'O...OO',
  v: 'O.O.OO',
  w: '.OOO.O',
  x: 'OO..OO',
  y: 'OO.OOO',
  z: 'O..OOO',
  ' ': '......',
  '.': '..OO.O',
  ',': '..O...',
  ';': '..O.O.',
  ':': '..OO..',
  '!': '..OOO.',
  '?': '..O.OO',
  '(': 'O.O..O',
  ')': '.O.OO.',
  '-': '....OO',
  '<': '.OO..O',
  '>': 'O..OO.',
} as const;

export const modifyiers = {
  capitalFollows: '.....O',
  decimalFollows: '.O...O',
  numberFollows: '.O.OOO',
} as const;
