dictionary = {
  'A': 'o.....',
  'B': 'o.o...',
  'C': 'oo....',
  'D': 'oo.o..',
  'E': 'o..o..',
  'F': 'ooo...',
  'G': 'oooo..',
  'H': 'o.oo..',
  'I': '.oo...',
  'J': '.ooo..',
  'K': 'o...o.',
  'L': 'o.o.o.',
  'M': 'oo..o.',
  'N': 'oo.oo.',
  'O': 'o..oo.',
  'P': 'ooo.o.',
  'Q': 'ooooo.',
  'R': 'o.ooo.',
  'S': '.oo.o.',
  'T': '.oooo.',
  'U': 'o...oo',
  'V': 'o.o.oo',
  'W': '.ooo.o',
  'X': 'oo..oo',
  'Y': 'oo.ooo',
  'Z': 'o..ooo',
  'a': 'o.....',
  'b': 'o.o...',
  'c': 'oo....',
  'd': 'oo.o..',
  'e': 'o..o..',
  'f': 'ooo...',
  'g': 'oooo..',
  'h': 'o.oo..',
  'i': '.oo...',
  'j': '.ooo..',
  'k': 'o...o.',
  'l': 'o.o.o.',
  'm': 'oo..o.',
  'n': 'oo.oo.',
  'o': 'o..oo.',
  'p': 'ooo.o.',
  'q': 'ooooo.',
  'r': 'o.ooo.',
  's': '.oo.o.',
  't': '.oooo.',
  'u': 'o...oo',
  'v': 'o.o.oo',
  'w': '.ooo.o',
  'x': 'oo..oo',
  'y': 'oo.ooo',
  'z': 'o..ooo',
  '1': 'o.....',
  '2': 'o.o...',
  '3': 'oo....',
  '4': 'oo.o..',
  '5': 'o..o..',
  '6': 'ooo...',
  '7': 'oooo..',
  '8': 'o.oo..',
  '9': '.oo...',
  '0': '.ooo..',
  'capital follows': '....o',
  'decimal follows': '.o...o',
  'number follows': '.o.ooo',
  '.': '..oo.o',
  ',': '..o...',
  '?': '..o.oo',
  '!': '..ooo.',
  ':': '..oo..',
  ';': '..o.o.',
  '-': '....oo',
  '/': '.o..o.',
  '<': '.oo..o',
  '>': 'o..oo.',
  '(': 'o.o..o',
  ')': '.o.oo.',
  ' ': '......',
  'o.....': 'A',
  'o.o...': 'B',
  'oo....': 'C',
  'oo.o..': 'D',
  'o..o..': 'E',
  'ooo...': 'F',
  'oooo..': 'G',
  'o.oo..': 'H',
  '.oo...': 'I',
  '.ooo..': 'J',
  'o...o.': 'K',
  'o.o.o.': 'L',
  'oo..o.': 'M',
  'oo.oo.': 'N',
  'o..oo.': 'O',
  'ooo.o.': 'P',
  'ooooo.': 'Q',
  'o.ooo.': 'R',
  '.oo.o.': 'S',
  '.oooo.': 'T',
  'o...oo': 'U',
  'o.o.oo': 'V',
  '.ooo.o': 'W',
  'oo..oo': 'X',
  'oo.ooo': 'Y',
  'o..ooo': 'Z',
  '..oo.o': '.',
  '..o...': ',',
  '..o.oo': '?',
  '..ooo.': '!',
  '..oo..': ':',
  '..o.o.': ';',
  '....oo': '-',
  '.o..o.': '/',
  '.oo..o': '<',
  # 'o..oo.': '>',
  'o.o..o': '(',
  '.o.oo.': ')',
  '......': ' ',
  '....o': 'capital follows',
  '.o...o': 'decimal follows',
  '.o.ooo': 'number follows'

}

dictionary_number = {
  'o.....': '1',
  'o.o...': '2',
  'oo....': '3',
  'oo.o..': '4',
  'o..o..': '5',
  'ooo...': '6',
  'oooo..': '7',
  'o.oo..': '8',
  '.oo...': '9',
  '.ooo..': '0',
}
