braille_to_english = {
    "O.....": 'a1',
    "O.O...": 'b2',
    "OO....": 'c3',
    "OO.O..": 'd4',
    "O..O..": 'e5',
    "OOO...": 'f6',
    "OOOO..": 'g7',
    "O.OO..": 'h8',
    ".OO...": 'i9',
    ".OOO..": 'j0',
    "O...O.": 'k',
    "O.O.O.": 'l',
    "OO..O.": 'm',
    "OO.OO.": 'n',
    "O..OO.": 'o',
    "OOO.O.": 'p',
    "OOOOO.": 'q',
    "O.OOO.": 'r',
    ".OO.O.": 's',
    ".OOOO.": 't',
    "O...OO": 'u',
    "O.O.OO": 'v',
    ".OOO.O": 'w',
    "OO..OO": 'x',
    "OO.OOO": 'y',
    "O..OOO": 'z',
    "......": ' ',
    ".....O": 'CAPITAL',
    ".O.OOO": 'NUMBER'
}
