import sys #to run the command line interface
RULES_TO_BRAILLE={
    'capital':'.....O',
    'decimal':'.O...O',
    'number':'.O.OOO'
}
SYMBOLS_TO_BRAILLE={
    '.':'..OO.O',
    ',':'..O...',
    '?':'..O.OO',
    '!':'..OOO.',
    ':':'..OO..',
    ';':'..O.O.',
    '-':'....OO',
    '/':'.O..O.',
    '<':'.OO..O',
    '>':'O..OO.',
    '(':'O.O..O',
    ')':'.O.OO.',
    ' ':'......'
}
LETTERS_TO_BRAILLE={
    'a':'O.....',
    'b':'O.O...',
    'c':'OO....',
    'd':'OO.O..',
    'e':'O..O..',
    'f':'OOO...',
    'g':'OOOO..',
    'h':'O.OO..',
    'i':'O.O...',
    'j':'.OOO..',
    'k':'O...O.',
    'l':'O.O.O.',
    'm':'OO..O.',
    'n':'OO.OO.',
    'o':'O..OO.',
    'p':'OOO.O.',
    'q':'OOOOO.',
    'r':'O.OOO.',
    's':'.OO.O.',
    't':'.OOOO.',
    'u':'O...OO',
    'v':'O.O.OO',
    'w':'.OOO.O',
    'x':'OO..OO',
    'y':'OO.OOO',
    'z':'O..OOO'
}
NUMBERS_TO_BRAILLE={
    '1':'O.....',
    '2':'O.O...',
    '3':'OO....',
    '4':'OO.O..',
    '5':'O..O..',
    '6':'OOO...',
    '7':'OOOO..',
    '8':'O.OO..',
    '9':'O.O...',
    '0':'.OOO..',     
}


