name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "javascript/**"

jobs:
  javascript-tests:
    name: Run JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          cd javascript
          npm install
      - name: Run tests
        run: |
          cd javascript
          npm test
